filebeat.config:
  modules:
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

setup.kibana:
  host: kibana:5601

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: elastic
  password: changeme
