ARG BEATS_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/beats/filebeat:${ELK_VERSION}

# Add your filebeat plugins setup here
# Example: RUN filebeat modules enable <name>

RUN filebeat modules enable cisco